version: '3'

services:
  strapi:
    build:
      context: .
    ports:
      - "1337:1337"
    volumes:
      # This maps your local .tmp folder to the container's .tmp folder
      - ./.tmp:/opt/app/.tmp
      - ./public/uploads:/opt/app/public/uploads
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
    restart: unless-stopped
